"""Core types, errors, schemas, and logging for trade_advisor."""

from __future__ import annotations

from trade_advisor.core.errors import (
    BiasDetectionError,
    BoundaryViolationError,
    ComputationError,
    ConfigurationError,
    ConvergenceError,
    DataError,
    DataGapError,
    FeatureComputationError,
    InsufficientHistoryError,
    IntegrityError,
    LookaheadBiasError,
    QTAError,
    StaleDataError,
    SurvivorshipBiasError,
)
from trade_advisor.core.logging import configure_logging, get_logger
from trade_advisor.core.schemas import (
    ErrorDetail,
    ErrorResponse,
    PaginatedResponse,
    PaginationMeta,
    SuccessResponse,
)
from trade_advisor.core.types import (
    CRYPTO,
    EQUITY,
    FX,
    BasisPoints,
    Currency,
    Notional,
    PrecisionPolicy,
    Price,
    Quantity,
    Returns,
    Side,
    Signal,
    Timestamp,
    decimal_to_str,
    from_float,
    log_to_simple,
    simple_to_log,
    to_float,
)

__all__ = [
    "CRYPTO",
    "EQUITY",
    "FX",
    "BasisPoints",
    "BiasDetectionError",
    "BoundaryViolationError",
    "ComputationError",
    "ConfigurationError",
    "ConvergenceError",
    "Currency",
    "DataError",
    "DataGapError",
    "ErrorDetail",
    "ErrorResponse",
    "FeatureComputationError",
    "InsufficientHistoryError",
    "IntegrityError",
    "LookaheadBiasError",
    "Notional",
    "PaginatedResponse",
    "PaginationMeta",
    "PrecisionPolicy",
    "Price",
    "QTAError",
    "Quantity",
    "Returns",
    "Side",
    "Signal",
    "StaleDataError",
    "SuccessResponse",
    "SurvivorshipBiasError",
    "Timestamp",
    "configure_logging",
    "decimal_to_str",
    "from_float",
    "get_logger",
    "log_to_simple",
    "simple_to_log",
    "to_float",
]
