#!/usr/bin/env python3
"""Bridge: Serena memories → BMAD context injection.

Reads all Serena memories and generates a unified context file
that BMAD skills can reference before execution.

Usage:
    python scripts/serena-context-for-bmad.py [--output CONTEXT_FILE]
"""
import json
import sys
import argparse
from pathlib import Path
from datetime import datetime


def load_all_memories(memories_dir: Path) -> dict:
    memories = {}
    if not memories_dir.exists():
        return memories
    for mem_file in sorted(memories_dir.glob("*.md")):
        name = mem_file.stem.replace("_", "/")
        try:
            memories[name] = mem_file.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            memories[name] = mem_file.read_text(encoding="latin-1")
    return memories


def generate_unified_context(memories: dict) -> str:
    sections = []
    sections.append("# Unified Integration Context")
    sections.append(f"Generated: {datetime.now().isoformat()}")
    sections.append("")
    sections.append("This file is auto-generated by the BMAD-Serena-Graphify integration layer.")
    sections.append("BMAD skills should read this file before execution for enriched context.")
    sections.append("")

    if "bmad/current-phase" in memories:
        sections.append("## BMAD Phase")
        sections.append(memories["bmad/current-phase"])
        sections.append("")

    if "bmad/sprint-summary" in memories:
        sections.append("## Sprint Status")
        sections.append(memories["bmad/sprint-summary"])
        sections.append("")

    if "bmad/decisions" in memories:
        sections.append("## Key Decisions (PRD + Architecture)")
        sections.append(memories["bmad/decisions"])
        sections.append("")

    if "bmad/epics" in memories:
        sections.append("## Epics Overview")
        sections.append(memories["bmad/epics"])
        sections.append("")

    if "bmad/agent-insights" in memories:
        sections.append("## Agent Insights (Fei-Fei + Fisher)")
        sections.append(memories["bmad/agent-insights"])
        sections.append("")

    if "graphify/communities" in memories:
        sections.append("## Code Communities (from Knowledge Graph)")
        sections.append(memories["graphify/communities"])
        sections.append("")

    if "graphify/god-nodes" in memories:
        sections.append("## God Nodes (Core Abstractions)")
        sections.append(memories["graphify/god-nodes"])
        sections.append("")

    if "graphify/dependencies" in memories:
        sections.append("## Cross-Community Dependencies")
        sections.append(memories["graphify/dependencies"])
        sections.append("")

    if "graphify/surprising" in memories:
        sections.append("## Surprising Connections")
        sections.append(memories["graphify/surprising"])
        sections.append("")

    if "graphify/hyperedges" in memories:
        sections.append("## Hyperedges (Group Relationships)")
        sections.append(memories["graphify/hyperedges"])
        sections.append("")

    if "integration/sync-log" in memories:
        sections.append("## Sync Log")
        sections.append(memories["integration/sync-log"])
        sections.append("")

    return "\n".join(sections)


def generate_compact_context(memories: dict) -> str:
    sections = []
    sections.append("# Compact Context (for BMAD skill injection)")
    sections.append(f"Generated: {datetime.now().isoformat()}")
    sections.append("")

    for key in ["bmad/current-phase", "bmad/sprint-summary"]:
        if key in memories:
            content = memories[key]
            lines = content.splitlines()
            summary = "\n".join(lines[:15])
            sections.append(f"## {key}")
            sections.append(summary)
            sections.append("")

    for key in ["graphify/communities", "graphify/god-nodes"]:
        if key in memories:
            content = memories[key]
            lines = content.splitlines()
            summary = "\n".join(lines[:20])
            sections.append(f"## {key}")
            sections.append(summary)
            sections.append("")

    return "\n".join(sections)


def main():
    parser = argparse.ArgumentParser(description="Serena → BMAD context bridge")
    parser.add_argument("--output", type=str, default="_bmad-output/unified-context.md", help="Output context file")
    parser.add_argument("--compact", type=str, default="_bmad-output/compact-context.md", help="Compact context file")
    args = parser.parse_args()

    memories_dir = Path(".serena/memories")
    print("Serena → BMAD Context Bridge")
    print(f"Reading memories from: {memories_dir.resolve()}")

    memories = load_all_memories(memories_dir)
    print(f"  Loaded {len(memories)} memories")

    if not memories:
        print("  WARNING: No memories found. Run graphify-to-serena.py and bmad-to-serena.py first.")
        sys.exit(1)

    unified = generate_unified_context(memories)
    compact = generate_compact_context(memories)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(unified)
    print(f"  Written: {output_path} ({len(unified)} chars)")

    compact_path = Path(args.compact)
    compact_path.write_text(compact)
    print(f"  Written: {compact_path} ({len(compact)} chars)")

    print("\nDone. Context files ready for BMAD skill injection.")


if __name__ == "__main__":
    main()
